### ISSUE TITLE
about my language rawscript

### ISSUE THREAD

**Issue by Kashina69** [TENTHER101/TEPL#4]
broo sorry for makign issues in your personal repo but as i can see that you have seen a lot of progamming languages which are really good and trying to solve the problem which i am trying to solve so tell me is my language is different or is it some new programming language i n the pool of custom english to progamming language interpraters plzz help and i am not able to find the documentation of your langauge how to use it wait let me download the code and see the updated code style i will put it soon
and can you contact me on discord on id 1021628209692942387 
have a lot of question which can only ask on a voice massage thing plzz if you have time

**Comment by TENTHER101** [comment]
Nono, you're good. Yes, I have seen many, and used many as well. Well first of all, I'd prefer it if you use no foul language on any of my repos as I like to keep it for all ages, and second of all, your language has some unique things in it, for example, it allows the programmer to translate the code into a variety of languages(by the way, you do know you're building a compiler, right?). The documentation can be found [here](https://tepl.vercel.app/docs.html). I do not use discord so we can easily just talk on here instead if you wish to ask any questions. 

Happy coding!
